Add bucket for `self::*` selector and change unit-tests
FontoXML/fontoxpath pull request #275
Opened 2020-10-01 12:56 UTC by Abbasi-Waqas

2020-10-02 10:17 UTC, bwrrp requested changes

2020-10-02 10:17 UTC, bwrrp commented on test/specs/parsing/tests/NameTest.tests.ts
>  			chai.assert.isNull(getBucketForSelector('self::*[@attr]'));
You should probably also update this one?

2020-10-05 08:36 UTC, DrRataplan approved these changes

2020-10-05 08:51 UTC, DrRataplan commented
There is one line newly uncovered (https://coveralls.io/builds/33926049/source?filename=src%2Fexpressions%2Faxes%2FParentAxis.ts#L42). Could you check that out?

2020-10-05 15:56 UTC, JosVerburg approved these changes

2020-10-06 07:27 UTC, bwrrp approved these changes

2020-10-07 11:44 UTC, merged