Add fn:format-integer with supported pictures: "A", "a", "I" and "i"
FontoXML/fontoxpath pull request #520
Opened 2022-08-12 13:49 UTC by rebp

2022-08-15 15:22 UTC, DrRataplan commented
Awesome!

Can you:

* Run the linter (`npm run lint-fix`)
* Remove the `only`,
* Check whether all other unit tests work?

I'll look further into this tomorrow!

2022-08-16 12:42 UTC, rebp commented
Ran the tests and only 17 were pending, the rest did passed

2022-08-18 07:09 UTC, DrRataplan requested changes

2022-08-18 07:09 UTC, DrRataplan commented on src/expressions/functions/builtInFunctions_numeric.ts
> +	const romanNumbers = [
lets pull this to the module scope

2022-08-18 07:09 UTC, DrRataplan commented on src/expressions/functions/builtInFunctions_numeric.ts
> +	let int = parseInt(integer);
Can you make this parseInt(integer, 10)? That fixes the linter error

2022-08-18 07:09 UTC, DrRataplan commented on src/expressions/functions/builtInFunctions_numeric.ts
> +	const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
Can you pull this to the module lvl?

2022-08-18 07:09 UTC, DrRataplan commented on src/expressions/functions/builtInFunctions_numeric.ts
> +	let int = parseInt(integer);
Also add `10` here as a second param

2022-08-18 12:06 UTC, DrRataplan commented
Can you fix the last linter errors?

```/home/runner/work/fontoxpath/fontoxpath/src/expressions/functions/builtInFunctions_numeric.ts:63:2
ERROR: 63:2  semicolon  Unnecessary semicolon
ERROR: 87:2  semicolon  Unnecessary semicolon```

2022-08-18 13:09 UTC, DrRataplan approved these changes

2022-08-18 13:19 UTC, merged